apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: contact-record
resources:
  - namespace.yaml
  - postgres.yaml
  - backend-configmap.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
